/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.OrganizerRole;

import Business.Application.SplitVolunteerRequest;
import Business.Organization.FundRaiserOrganization;
import Business.UserAccount.UserAccount;
import Business.UserAccount.VolunteerAccount;
import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author pavanrao
 */
public class VolunteerPerformanceJPanel extends javax.swing.JPanel {

    /**
     * Creates new form VolunteerPerformanceJPanel
     */
    JPanel userProcessContainer;
    FundRaiserOrganization fundRaiserOrg;
    UserAccount userAccount;
    List<VolunteerAccount> volunteerList;

    VolunteerPerformanceJPanel(JPanel userProcessContainer, FundRaiserOrganization fundRaiserOrg, UserAccount userAccount, List<VolunteerAccount> volunteerList) {
        this.userProcessContainer = userProcessContainer;
        this.fundRaiserOrg = fundRaiserOrg;
        this.userAccount = userAccount;
        this.volunteerList = volunteerList;
        initComponents();   
        populateTable();
    }

    public void populateTable(){
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        model.setRowCount(0);

        for(VolunteerAccount vol: volunteerList){
            Object[] row = new Object[2];
            row[1] = vol;
            row[0] = vol.getEmployee().getId();
            model.addRow(row);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setLayout(null);

        jButton1.setText("VIEW PERFORMANCE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(190, 530, 186, 41);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Volunteer Id", "Volunteer Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1);
        jScrollPane1.setBounds(59, 99, 294, 389);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Volunteer Performance Dashboard");
        add(jLabel1);
        jLabel1.setBounds(530, 30, 360, 33);

        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));
        add(jPanel2);
        jPanel2.setBounds(446, 99, 970, 690);

        jButton2.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2);
        jButton2.setBounds(50, 530, 90, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon("/Users/apple/Downloads/images-for-fr/volvol.jpeg")); // NOI18N
        jLabel2.setText("jLabel2");
        add(jLabel2);
        jLabel2.setBounds(0, 0, 1590, 1010);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        DefaultCategoryDataset barchartdata = new DefaultCategoryDataset();
//        barchartdata.setValue(108, "Target Amount", "Application1");
//        barchartdata.setValue(98, "Amount Achieved", "Application1");
//        barchartdata.setValue(58, "Target Amount", "Application2");
//        barchartdata.setValue(60, "Amount Achieved", "Application2");
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow >= 0) {
            
            VolunteerAccount vol = (VolunteerAccount) jTable1.getValueAt(selectedRow, 1);
            List<SplitVolunteerRequest> volReqList = vol.getAssignedSplitRequestList();
            int i=0;
            for(SplitVolunteerRequest volReq: volReqList) {
                ++i;
                barchartdata.setValue(volReq.getSplitAmount(), "Target Amount", "Work Request "+i);
                barchartdata.setValue(volReq.getAmountAchieved(), "Amount Achieved", "Work Request "+i);
            }
        }
        
        JFreeChart barchart = ChartFactory.createBarChart3D("Volunteer Performance", "Work Requests", "Amount", barchartdata, PlotOrientation.VERTICAL, true, true, false);
        
        CategoryPlot barCh = barchart.getCategoryPlot();
        barCh.setRangeGridlinePaint(Color.ORANGE);
        
        ChartPanel chartPanel = new ChartPanel(barchart);
        jPanel2.removeAll();
        jPanel2.add(chartPanel);
        jPanel2.updateUI();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
