/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.BackgroundCheckRole;

import Business.Application.Application;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.FundRaiserOrganization;
import Business.Organization.Organization;
import Business.WorkQueue.WorkRequest;
import javax.swing.JPanel;
import Business.Utils.BusinessStatus;
import Business.Utils.BusinessUtils;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import java.net.URL;
import java.io.*;
import java.net.MalformedURLException;
import java.net.URLConnection;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import javax.net.ssl.HttpsURLConnection;
import javax.swing.table.DefaultTableModel;
import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;
import userinterface.MainJFrame;
import org.apache.log4j.Logger;

public class BackgroundTakeActionJPanel extends javax.swing.JPanel {

    /**
     * Creates new form BackgroundTakeActionJPanel
     */
    private JPanel userProcessContainer;
    private WorkRequest wr;
    private EcoSystem business;
    private FundRaiserOrganization fundRaiserOrganization;
    private Enterprise enterprise;
    final Logger logger = Logger.getLogger(MainJFrame.class);
    
    public BackgroundTakeActionJPanel(JPanel userProcessContainer, WorkRequest wr, EcoSystem business, FundRaiserOrganization fundRaiserOrganization, Enterprise enterprise) throws MalformedURLException {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.wr=wr;
        this.business = business;
        this.fundRaiserOrganization = fundRaiserOrganization;
        this.enterprise = enterprise;
        lblPayee.setText(wr.getSender().getEmployee().getName());
        lblAmount.setText(Double.toString(wr.getSender().getWalletMoney()));
        lblCause.setText(((Application)wr).getCause());
        lblRequestedMoney.setText(((Application)wr).getAmountRequested().toString());
    }

    public void getFraudstersInfo() throws MalformedURLException, IOException, JSONException {
        String fullName = wr.getSender().getEmployee().getName();
        fullName = fullName.replace(" ", "%20");

        URL fraudster = new URL("http://nflArrest.com/api/v1/player/arrests/"+fullName);
        URLConnection yc = fraudster.openConnection();
        BufferedReader in = new BufferedReader(
                                new InputStreamReader(
                                yc.getInputStream()));
        String inputLine;
        StringBuilder response = new StringBuilder("{ 'response':");
        while ((inputLine = in.readLine()) != null) {
            response.append(inputLine);
            logger.info(inputLine);
        }
        response.append("}");
        in.close();
        
        JSONObject jsonObject = new JSONObject(response.toString());
        JSONArray tsmresponse = (JSONArray) jsonObject.getJSONArray("response");

        Map<String, String> responseMap = new HashMap<String, String>();
        
        if(tsmresponse.length()>0) {
            
            for(int i=0; i<tsmresponse.length(); i++)
                responseMap.put(tsmresponse.getJSONObject(i).getString("arrest_stats_id"), tsmresponse.getJSONObject(i).getString("Encounter"));

            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

            model.setRowCount(0);

            JOptionPane.showMessageDialog(null,"Payee has criminal background. It is advisable not to proceed with this application!");
            logger.info("Payee has criminal background. It is advisable not to proceed with this application!");
            for (Map.Entry<String,String> entry : responseMap.entrySet())  {
                Object[] row = new Object[2];
                row[0] = entry.getKey();
                row[1] = entry.getValue();
                model.addRow(row);
            }
                 
        }
        
        else {
            JOptionPane.showMessageDialog(null,"Payee is not a fraud as per our records. You're free to procees with next steps!");
            logger.info("Payee is not a fraud as per our records. You're free to procees with next steps!");
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        lblPayee = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblAmount = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblCause = new javax.swing.JLabel();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtComments = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jCheckBox4 = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        lblRequestedMoney = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 2, 14)); // NOI18N
        jLabel1.setText("Payee  :");
        add(jLabel1);
        jLabel1.setBounds(119, 92, 51, 17);

        lblPayee.setFont(new java.awt.Font("Lucida Grande", 2, 14)); // NOI18N
        lblPayee.setText("<payee>");
        add(lblPayee);
        lblPayee.setBounds(176, 92, 62, 17);

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 2, 14)); // NOI18N
        jLabel3.setText("Payee's Wallet Money  :");
        add(jLabel3);
        jLabel3.setBounds(119, 156, 155, 17);

        lblAmount.setFont(new java.awt.Font("Lucida Grande", 2, 14)); // NOI18N
        lblAmount.setText("<amount>");
        add(lblAmount);
        lblAmount.setBounds(280, 156, 75, 17);

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 2, 14)); // NOI18N
        jLabel5.setText("Cause  :");
        add(jLabel5);
        jLabel5.setBounds(119, 191, 54, 17);

        lblCause.setFont(new java.awt.Font("Lucida Grande", 2, 14)); // NOI18N
        lblCause.setText("<cause>");
        add(lblCause);
        lblCause.setBounds(179, 191, 61, 17);

        jCheckBox2.setFont(new java.awt.Font("Lucida Grande", 2, 14)); // NOI18N
        jCheckBox2.setText("Amount < 2*Wallet Amount");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });
        add(jCheckBox2);
        jCheckBox2.setBounds(109, 269, 222, 23);

        jCheckBox3.setFont(new java.awt.Font("Lucida Grande", 2, 14)); // NOI18N
        jCheckBox3.setText("Physical Inspected");
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });
        add(jCheckBox3);
        jCheckBox3.setBounds(109, 351, 156, 23);

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 2, 14)); // NOI18N
        jLabel7.setText("Comments");
        add(jLabel7);
        jLabel7.setBounds(109, 461, 74, 17);

        txtComments.setColumns(20);
        txtComments.setRows(5);
        jScrollPane1.setViewportView(txtComments);

        add(jScrollPane1);
        jScrollPane1.setBounds(231, 461, 396, 105);

        jButton1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jButton1.setText("Approve");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(303, 610, 122, 52);

        jButton2.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jButton2.setText("Reject");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2);
        jButton2.setBounds(508, 610, 119, 52);

        jButton3.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3);
        jButton3.setBounds(109, 610, 116, 52);

        jTable1.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Arrest ID", "Encounter"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);

        add(jScrollPane2);
        jScrollPane2.setBounds(777, 256, 581, 310);

        jButton4.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jButton4.setText("SEARCH FRAUDSTERS BY PAYEE'S NAME");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        add(jButton4);
        jButton4.setBounds(777, 132, 581, 51);

        jCheckBox4.setFont(new java.awt.Font("Lucida Grande", 2, 14)); // NOI18N
        jCheckBox4.setText("Not Fraudster");
        jCheckBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox4ActionPerformed(evt);
            }
        });
        add(jCheckBox4);
        jCheckBox4.setBounds(109, 310, 126, 23);

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 2, 14)); // NOI18N
        jLabel2.setText("Requested Money : ");
        add(jLabel2);
        jLabel2.setBounds(119, 121, 133, 17);

        lblRequestedMoney.setFont(new java.awt.Font("Lucida Grande", 2, 14)); // NOI18N
        lblRequestedMoney.setText("<money>");
        add(lblRequestedMoney);
        lblRequestedMoney.setBounds(270, 121, 68, 17);

        jLabel4.setIcon(new javax.swing.ImageIcon("/Users/apple/Downloads/images-for-fr/payee3.jpg")); // NOI18N
        add(jLabel4);
        jLabel4.setBounds(0, 0, 0, 0);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Take Action");
        add(jLabel6);
        jLabel6.setBounds(518, 17, 105, 22);

        jLabel8.setIcon(new javax.swing.ImageIcon("/Users/apple/Downloads/images-for-fr/payee3.jpg")); // NOI18N
        add(jLabel8);
        jLabel8.setBounds(0, 0, 1600, 1220);
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(!jCheckBox2.isSelected() && !jCheckBox4.isSelected() && !jCheckBox3.isSelected()){
            JOptionPane.showMessageDialog(null,"Please select one of the check boxes for taking action on this request!");
            return;
        }
        
        wr.setStatus(BusinessStatus.BckgrdChkApp.getValue());
        BusinessUtils.addToNextQueue(fundRaiserOrganization, Organization.Type.DigitalMarketing, wr, this.business, this.enterprise);
        JOptionPane.showMessageDialog(null,"Approved Successfully");
        
        if(BusinessUtils.sendEmail(((Application)wr).getPayeeEmail()
                ,"Your application's background check for "+((Application)wr).getCause()+" cause is "
                        + "successfully completed and is good to go!","Information regarding your new "
                                + "Fund Request").equals("unsuccessful")){
//            return;
        }
        
        //clear
        ButtonGroup bg = new ButtonGroup();
        bg.add(jCheckBox4);
        bg.add(jCheckBox2);
        bg.add(jCheckBox3);
        bg.clearSelection();
        txtComments.setText("");
        
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        BackgroundCheckWorkAreaJPanel sysAdminwjp = (BackgroundCheckWorkAreaJPanel) component;
        sysAdminwjp.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        wr.setStatus(BusinessStatus.BckgrdChkRej.getValue());
        JOptionPane.showMessageDialog(null,"Rejected Successfully");
        
        if(BusinessUtils.sendEmail(((Application)wr).getPayeeEmail()
                ,"Your application's background check for "+((Application)wr).getCause()+" cause was unsuccessfull and we regret to inform you that we cannot move forward with your request!","Information regarding your new Fund Request").equals("unsuccessful")){
//            return;
        }
        
        //clear
        ButtonGroup bg = new ButtonGroup();
        bg.add(jCheckBox4);
        bg.add(jCheckBox2);
        bg.add(jCheckBox3);
        bg.clearSelection();
        txtComments.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        BackgroundCheckWorkAreaJPanel sysAdminwjp = (BackgroundCheckWorkAreaJPanel) component;
        sysAdminwjp.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
            // TODO add your handling code here:
            getFraudstersInfo();
        } catch (IOException ex) {
            logger.info("Exception occured in "+BackgroundTakeActionJPanel.class.getName()+" and the exception is "+ex);
        } catch (JSONException ex) {
            java.util.logging.Logger.getLogger(BackgroundTakeActionJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jCheckBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblAmount;
    private javax.swing.JLabel lblCause;
    private javax.swing.JLabel lblPayee;
    private javax.swing.JLabel lblRequestedMoney;
    private javax.swing.JTextArea txtComments;
    // End of variables declaration//GEN-END:variables
}
