/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.DigitalMarketingRole;

import Business.Application.Application;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.DigitalMarketingOrganisation;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import Business.Utils.BusinessStatus;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import org.apache.log4j.Logger;
import userinterface.MainJFrame;
import userinterface.WalletDialogBox.TopUp;

/**
 *
 * @author raunak
 */
public class DigitalMarketingWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private DigitalMarketingOrganisation digitalMarketingOrganization;
    private EcoSystem business;
    final Logger logger = Logger.getLogger(MainJFrame.class);

    /**
     * Creates new form DoctorWorkAreaJPanel
     */
    public DigitalMarketingWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, 
            DigitalMarketingOrganisation digitalMarketingOrganization, Enterprise enterprise
        ,EcoSystem business) {
        initComponents();

        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.userAccount = account;
        this.digitalMarketingOrganization = digitalMarketingOrganization;
        lblWelcome.setText("Welcome "+account.getEmployee().getName());
        this.business = business;
        
        //pouplating the wallet ammount
        lblWalletAmt.setText("Wallet money: "+Double.toString(account.getWalletMoney()));

        populateRequestTable();
    }
    
    public void refresh(){
        lblWalletAmt.setText("Wallet money: "+Double.toString(userAccount.getWalletMoney()));
    }

    public void populateRequestTable() {

        DefaultTableModel model = (DefaultTableModel) workRequestJTable.getModel();

        model.setRowCount(0);

       
        for (WorkRequest request : digitalMarketingOrganization.getWorkQueue()
                .getWorkRequestList()) {
            
            String status = ((Application)request).getStatus();
            
            if(status.equals(BusinessStatus.BckgrdChkApp.getValue()) || 
                    status.equals(BusinessStatus.Advertised.getValue())) {
             
                Object[] row = new Object[5];
                row[0] = request;
                row[1] = ((Application)request).getAmountRequested();
                DateFormat dateFormat = new SimpleDateFormat("MM/dd/yyyy");

                row[2] = dateFormat.format(((Application)request).getRequiredBy());
                row[3] = ((Application)request).getCause();
                row[4] = status;
                model.addRow(row);
                
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        workRequestJTable = new javax.swing.JTable();
        requestTestJButton = new javax.swing.JButton();
        lblWelcome = new javax.swing.JLabel();
        lblWalletAmt = new javax.swing.JLabel();
        btnTopUp = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(null);

        workRequestJTable.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        workRequestJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Payee", "Amount", "Amount Required By", "Cause", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(workRequestJTable);

        add(jScrollPane1);
        jScrollPane1.setBounds(147, 202, 1051, 197);

        requestTestJButton.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        requestTestJButton.setText("View Request");
        requestTestJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestTestJButtonActionPerformed(evt);
            }
        });
        add(requestTestJButton);
        requestTestJButton.setBounds(585, 477, 246, 56);

        lblWelcome.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblWelcome.setText("Welcome,");
        add(lblWelcome);
        lblWelcome.setBounds(95, 72, 340, 30);

        lblWalletAmt.setFont(new java.awt.Font("Lucida Grande", 2, 14)); // NOI18N
        lblWalletAmt.setText("Wallet Amount: $x");
        add(lblWalletAmt);
        lblWalletAmt.setBounds(1110, 70, 140, 19);

        btnTopUp.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        btnTopUp.setText("TopUp Wallet");
        btnTopUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTopUpActionPerformed(evt);
            }
        });
        add(btnTopUp);
        btnTopUp.setBounds(1250, 60, 177, 43);

        jLabel1.setIcon(new javax.swing.ImageIcon("/Users/apple/Downloads/images-for-fr/dm.jpg")); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(0, 0, 1600, 1080);
    }// </editor-fold>//GEN-END:initComponents

    private void requestTestJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestTestJButtonActionPerformed

        int selectedRow = workRequestJTable.getSelectedRow();

        if (selectedRow >= 0) {

            WorkRequest wr = (WorkRequest) workRequestJTable.getValueAt(selectedRow, 0);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            userProcessContainer.add("DigitalMarketingWorkAreaRequestDetailsJPanel",
                    new DigitalMarketingWorkAreaRequestDetailsJPanel(userProcessContainer,
                            userAccount, enterprise, wr,business,digitalMarketingOrganization,this));
            layout.next(userProcessContainer);

        } else {
            JOptionPane.showMessageDialog(null, "Please select a row.");
            return;
        }
    }//GEN-LAST:event_requestTestJButtonActionPerformed

    private void btnTopUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTopUpActionPerformed
        // TODO add your handling code here:

        TopUp t=new TopUp(this.userAccount,this);
        t.setVisible(true);
    }//GEN-LAST:event_btnTopUpActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTopUp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblWalletAmt;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JButton requestTestJButton;
    private javax.swing.JTable workRequestJTable;
    // End of variables declaration//GEN-END:variables
}
