/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.VolunteerRoleJPanel;

import Business.Application.Application;
import Business.Application.SplitVolunteerRequest;
import Business.Enterprise.Enterprise;
import Business.Organization.FundRaiserOrganization;
import Business.UserAccount.UserAccount;
import Business.UserAccount.VolunteerAccount;
import Business.Utils.BusinessStatus;
import Business.WorkQueue.WorkRequest;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import org.apache.log4j.Logger;
import userinterface.OrganizerRole.OrganizerWorkAreaJPanel;
import userinterface.WalletDialogBox.TopUp;

/**
 *
 * @author pavanrao
 */
public class VolunteerWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form VolunteerWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private FundRaiserOrganization fundRaiserOrg;
    static final Logger logger = Logger.getLogger(OrganizerWorkAreaJPanel.class);
    
    public VolunteerWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, FundRaiserOrganization fundRaiserOrganization, Enterprise enterprise) {
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.userAccount = account;
        this.fundRaiserOrg=fundRaiserOrganization;
        
        //jLabel5.setText(enterprise.getName());
        initComponents();
        
        //welcome user
        lblWelcome.setText("Welcome "+account.getEmployee().getName()+"!");
        
        //populating the wallet amount
        lblWalletAmt.setText("Wallet money: "+Double.toString(account.getWalletMoney()));
        
        populateOpenTasksTable();
        populateAssignedTasks();
    }
    
    public void refresh(){
        lblWalletAmt.setText("Wallet money: "+Double.toString(userAccount.getWalletMoney()));
    }
    
    public void populateOpenTasksTable() {
        DefaultTableModel model = (DefaultTableModel)jTable2.getModel();
        
        model.setRowCount(0);
        
        DateFormat dateFormat = new SimpleDateFormat("MM/dd/yyyy");
        
        for(WorkRequest request : this.fundRaiserOrg.getWorkQueue().getWorkRequestList()){
            if(request instanceof SplitVolunteerRequest && ((SplitVolunteerRequest)request).getTaskStatus().equals(BusinessStatus.ReadyToPick.getValue())) {
                
            Object[] row = new Object[4];
            row[0] = request;
            row[1] = ((Application)request).getCause();
            row[2] = ((SplitVolunteerRequest)request).getSplitAmount();
            if(((Application)request).getRequiredBy() != null){
                row[3] = dateFormat.format(((Application)request).getRequiredBy());
            }
            
            model.addRow(row);
            }
        }
    }
    
    public void populateAssignedTasks() {
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        
        model.setRowCount(0);
        
        for(WorkRequest request : this.fundRaiserOrg.getWorkQueue().getWorkRequestList()){
            
            if(request instanceof SplitVolunteerRequest) {
                String taskStatus = ((SplitVolunteerRequest)request).getTaskStatus();
                if(((taskStatus.equals(BusinessStatus.InProgress.getValue())) ||
                     (taskStatus.equals(BusinessStatus.Fulfilled.getValue())) ||
                     (taskStatus.equals(BusinessStatus.UnFulfilled.getValue())) ) )  {
                
                    Object[] row = new Object[7];
                    row[0] = request;
                    row[1] = ((Application)request).getCause();
                    row[2] = ((SplitVolunteerRequest)request).getSplitAmount();
                    row[3] = ((SplitVolunteerRequest)request).getAmountAchieved();
                    row[4] = taskStatus;
                    row[5] = ((SplitVolunteerRequest)request).getAssignedToVolunteer().getUsername();
                    row[6] = ((SplitVolunteerRequest)request).getSplitAmountRequired();
                    model.addRow(row);
                }
            }
                    
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblWelcome = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        lblWalletAmt = new javax.swing.JLabel();
        btnTopUp = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(null);

        lblWelcome.setText("Welcome, ");
        add(lblWelcome);
        lblWelcome.setBounds(29, 25, 310, 63);

        jLabel3.setText("Search by Status:");
        add(jLabel3);
        jLabel3.setBounds(678, 88, 115, 37);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Payee", "Cause", "Target Amount", "Amount Achieved", "Status", "Assigned To", "Amount Required"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1);
        jScrollPane1.setBounds(475, 156, 565, 277);

        jLabel4.setText("OPEN TASKS");
        add(jLabel4);
        jLabel4.setBounds(155, 88, 99, 34);

        jButton4.setText("ASSIGN TO ME");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        add(jButton4);
        jButton4.setBounds(101, 493, 237, 55);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Payee", "Cause", "Target Amount", "Deadline"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        add(jScrollPane2);
        jScrollPane2.setBounds(41, 156, 404, 277);

        lblWalletAmt.setText("Wallet Amount: $x");
        add(lblWalletAmt);
        lblWalletAmt.setBounds(907, 24, 124, 19);

        btnTopUp.setText("TopUp Wallet");
        btnTopUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTopUpActionPerformed(evt);
            }
        });
        add(btnTopUp);
        btnTopUp.setBounds(923, 49, 108, 29);

        jLabel1.setIcon(new javax.swing.ImageIcon("/Users/apple/Downloads/images-for-fr/bc2n.jpg")); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(0, 0, 1750, 1150);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        int selectedRow = jTable2.getSelectedRow();

        if (selectedRow >= 0) {

            WorkRequest wr = (WorkRequest) jTable2.getValueAt(selectedRow, 0);
            ((SplitVolunteerRequest)wr).setTaskStatus(BusinessStatus.InProgress.getValue());
            ((SplitVolunteerRequest)wr).setAssignedToVolunteer((VolunteerAccount)userAccount);
            ((VolunteerAccount)userAccount).addAssignedSplitRequestList((SplitVolunteerRequest)wr);
            JOptionPane.showMessageDialog(null, "Successfully assigned the task to you");
            logger.info("Successfully assigned the task to "+userAccount.getEmployee().getName());
            populateAssignedTasks();
            populateOpenTasksTable();
            
        } else {
            JOptionPane.showMessageDialog(null, "Please select a row.");
            return;
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btnTopUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTopUpActionPerformed
        // TODO add your handling code here:

        TopUp t=new TopUp(this.userAccount,this);
        t.setVisible(true);
    }//GEN-LAST:event_btnTopUpActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTopUp;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel lblWalletAmt;
    private javax.swing.JLabel lblWelcome;
    // End of variables declaration//GEN-END:variables
}
